# Generated by Django 5.0.2 on 2024-02-25 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='movie',
            field=models.ForeignKey(db_column='movieId', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='movies.movie'),
        ),
    ]
